# Generated by Django 5.1.6 on 2025-02-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='can_create_tasks',
            new_name='can_assign_tasks',
        ),
    ]
