# Generated by Django 5.1.6 on 2025-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_completed_by_task_completed_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_bg', models.CharField(max_length=50)),
                ('tag_deriction', models.CharField(choices=[('full-stack', 'Full-stack'), ('back-end', 'Back-end'), ('front-end', 'Front-end'), ('ux-design', 'UX Design'), ('project-manager', 'Project Manager')], max_length=50)),
            ],
        ),
    ]
