# Generated by Django 5.1.6 on 2025-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tasktag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktag',
            options={'ordering': ['tag_deriction']},
        ),
        migrations.AddField(
            model_name='tasktag',
            name='tag_value',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('full-stack', 'Full-stack'), ('back-end', 'Back-end'), ('front-end', 'Front-end'), ('designer', 'Designer'), ('project-manager', 'Project Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='tag_deriction',
            field=models.CharField(choices=[('full-stack', 'Full-stack'), ('back-end', 'Back-end'), ('front-end', 'Front-end'), ('designer', 'Designer'), ('project-manager', 'Project Manager')], max_length=50),
        ),
    ]
