# Generated by Django 5.1.6 on 2025-02-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tasktag_options_tasktag_tag_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktag',
            name='tag_value',
        ),
    ]
