# Generated by Django 5.1.6 on 2025-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_task_assigned_to_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to='api.member'),
        ),
    ]
