# Generated by Django 5.1.6 on 2025-02-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
