# Generated by Django 5.1.6 on 2025-02-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_task_assigned_to_remove_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag_bg',
        ),
    ]
