# Generated by Django 5.1.6 on 2025-02-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_task_assigned_to_task_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(upload_to='tasks/'),
        ),
    ]
