# Generated by Django 5.1.6 on 2025-02-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_task_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
    ]
