# Generated by Django 5.1.6 on 2025-02-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('website.svg', 'WebSite'), ('webapp.svg', 'WebApp'), ('phone.svg', 'App'), ('bot.svg', 'Bot'), ('learning.svg', 'Learning'), ('excel.svg', 'Excel'), ('finance.svg', 'Finance')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_bg',
            field=models.CharField(choices=[('#FFEAF8', 'WebSite'), ('#DEEDFF', 'WebApp'), ('#E9E0F5', 'App'), ('#FFF8EA', 'Bot'), ('#FFEAF8', 'Learning'), ('#DEEDFF', 'Excel'), ('#E9E0F5', 'Finance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('WebSite', 'WebSite'), ('WebApp', 'WebApp'), ('App', 'App'), ('Bot', 'Bot'), ('Learning', 'Learning'), ('Excel', 'Excel'), ('Finance', 'Finance')], max_length=50),
        ),
    ]
