# Generated by Django 5.1.6 on 2025-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_icon_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon_bg',
            field=models.CharField(choices=[('FFEAF8', 'WebSite'), ('DEEDFF', 'WebApp'), ('E9E0F5', 'App'), ('FFF8EA', 'Bot'), ('FFEAF8', 'Learning'), ('DEEDFF', 'Excel'), ('E9E0F5', 'Finance')], max_length=20),
        ),
    ]
