# Generated by Django 5.1.6 on 2025-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_project_icon_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('webSite.svg', 'WebSite'), ('webApp.svg', 'WebApp'), ('app.svg', 'App'), ('bot.svg', 'Bot'), ('learning.svg', 'Learning'), ('excel.svg', 'Excel'), ('finance.svg', 'Finance')], max_length=255),
        ),
    ]
