# Generated by Django 5.1.6 on 2025-02-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon_bg',
            field=models.CharField(choices=[('FFEAF8', 'WebSite'), ('DEEDFF', 'WebApp'), ('E9E0F5', 'App'), ('FFF8EA', 'Bot'), ('FFEEEC', 'Learning'), ('D6E6FF', 'Excel'), ('E9D9FF', 'Finance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To do'), ('in-progress', 'In progress'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=20),
        ),
    ]
